version: '3.4'

services:
  cicdproject:
    image: cicdproject
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 3031:3031
      - 5005:5005
