version: "3.3"

services:
  box-hg-gateway:
    image: "ci-cd-project-homolog:${CODE_SC_HG}"
    ports:
      - 8383:3032
    environment:
      - nome.ambiente=Homologação
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
